spring.application.name=blood-donation
server.port=8060

#Spring Datasource Configuration for PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jooq.sql-dialect=POSTGRES

#Lifelink Configuration (window-minutes=30, check-interval-ms=300000)
lifelink.cascade.window-minutes=1 
lifelink.cascade.check-interval-ms=10000